fixtures:
  repositories:
    "puppi": "git://github.com/example42/puppi.git"
    "monitor": "git://github.com/example42/puppet-monitor.git"
    "concat": "git://github.com/ripienaar/puppet-concat.git"
  symlinks:
    "ddclient": "#{source_dir}"

